### ISSUE TITLE
🐛: React tool tip is not showing anything for the first day.

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#117]
## Describe the bug

The tool-tip hover popup is not showing for the first day. However there is data there on the heatmap and showing data on the habit details.

The third day the tool-tip is showing up.

## To Reproduce
Try to create a new habit and see if the data show up on the first day.

## Expected behavior
The tool-tip should be showing up for every entry.

### First Day
![image](https://user-images.githubusercontent.com/602422/57537198-c3ea5d00-7313-11e9-9ef3-ae7fc3737111.png)

### Third Day
![image](https://user-images.githubusercontent.com/602422/57537225-d5336980-7313-11e9-9d32-0f05fae413ef.png)

## Additional context
Add any other context about the problem her

**Comment by SaraSweetie** [comment]
@patricktownley might know why this is behaving this way. Originally the first day was not appearing on the calendar heat map and he fixed that bug to make that date appear.

**Comment by paulywill** [comment]
If we cannot figure this out asap I would like to revert #116 - Push Dev to Master and #113 - Colors and Null.

We may have some traffic coming in to check out our app this weekend.
Ideally things should be working smooth but just have #114 - Google Analytics added to the master.

**Comment by SaraSweetie** [comment]
The tooltip is working for me. Both in local, and the live heroku

Local npm start (below)
<img width="787" alt="Screen Shot 2019-05-11 at 8 46 27 AM" src="https://user-images.githubusercontent.com/33433415/57569888-b7c0d700-73c9-11e9-801f-aa1a814419d3.png">


heroku (below)
<img width="627" alt="Screen Shot 2019-05-11 at 8 47 24 AM" src="https://user-images.githubusercontent.com/33433415/57569887-b42d5000-73c9-11e9-84d8-ed40116e6b71.png">

**Comment by paulywill** [comment]
@pjconnolly12 @patricktownley  Is the tool-tip showing up fine for you?

**Comment by paulywill** [comment]
![B4E033A3-2229-460A-8AA5-55D187858FAB](https://user-images.githubusercontent.com/602422/57574991-32144a00-7410-11e9-86d6-0bc3eb423bbe.png)

Try testing with our V8 gmail account... only new entry is working for me.

EDIT: I am currently testing on mobile but my laptop was showing similar issue last night too.

**Comment by paulywill** [comment]
Thats odd. Working now for me. Perhaps async?
I’ll close this issue.
