### ISSUE TITLE
📝: CREATE v2.0

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#123]
## Task Description

@patricktownley @pjconnolly12 @SaraSweetie - Version 2?

## Function

Get the team back together for to level up skills

## Feature 

I'm currently back to learning and helping with a few open source projects but my skills are lacking. Specifically writing unti test and wrapping my head around React and it's never ending updates.

Let's face it we made a MVP but it did NOT live up to our intension. Specially, who would want to use it the way it is?

I'm thinking we could even create a slick chrome extension to do most of the settings and updates. The webpage would be for fancy dashboard and feedback.

If you're all bored and looking for an excuse to code something I think we could get this updated again.

Even make a repo/org separate from Chingu.

Let me know if you're any of you are interested.

**Comment by patricktownley** [comment]
Paul - I was just thinking about this project and crew the other day.  I am into the idea but don't have a ton of time right now.  Maybe a slack or discord group would be a good idea?

**Comment by paulywill** [comment]
I have both, good with either

EDIT: specifically... do you know how to setup one?

**Comment by pjconnolly12** [comment]
Hey guys! I would be interested in this. Since we finished I have pretty much been a traveling nomad so I have let my practice and learning drop off. Would love to get back on the right track! Abotu 2 weeks ago I started taking a Node course and refreshing my Javascript skills, so this was perfect timing!

**Comment by SaraSweetie** [comment]
Hello everyone! I've been very busy and haven't had much time to devote to
learning. I've been teaching a beginner web development course to women,
two nights a week. That's over at the end of November, and I was planning
on getting back to learning JavaScript more. I am also pregnant and
expecting a girl in Feb/March, so trying to clean out a room and learn
about babies (this will be my first) is taking up my time.

Soo.. I can't really commit a lot of time to this. But would be happy to
work on some stuff if needed, brainstorm, or test anything out. I have
Slack and Discord. I am more active with Slack and check it more often.

Sara

**Comment by paulywill** [comment]
Congrats @SaraSweetie!!! Yeah, your life is going to only get busier... but in good way :)


-----
~~So let's set something a room up in Slack.~~
Workspace created... invites sent.

No pressure this time around. We play when we can and want.
Ideally I like this version to be good enough that I find it useful for myself.
