### ISSUE TITLE
⭐: Initial login screen / official Google button :door:

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#41]
**User Story**

User is presented:

![Login screen](https://github.com/chingu-voyages/v8-geckos-team-07/blob/master/docs/01-login.png?raw=true)

**Acceptance Criteria**

- Login form comes up for any user that is not logged in. Firebase/"google-button" feature _should_ detect this.
- Official Google button from Google branding assets is used

**Definition of Done**
- Team is happy with result 🎉🎉🎉

**Comment by pjconnolly12** [comment]
I really like this!! My only suggestion would be to move the button up just a little, but like I've said before...I'm not a design specialist so I could be wrong.

**Comment by paulywill** [comment]
Here is the location of those buttons we can use: https://developers.google.com/identity/branding-guidelines
