### ISSUE TITLE
📝: CSS to resolve NewHabit modal functionality/placement

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#60]
## Task Description
@SaraSweetie suggested to @pjconnolly12 to look into CSS z-index and maybe new `<modal>` tag.

## Function
Have the function pop-up and display properly.

## Feature 
#11 - New Habit

*Do not forget to set Epic, Milestone, and Estimate (1 = half workday)!*

**Comment by pjconnolly12** [comment]
I have completed this enhancement, will push up the request soon for @SaraSweetie to review (and anyone else who wants to review)

**Comment by paulywill** [comment]
@pjconnolly12 I have reopened this by moving the card in my ZenHub to the "Done" column. When the PR is pushed and merge I will move it to close.
