### ISSUE TITLE
📝: Move the ‘red button’ into header as well

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#61]
## Task Description

The current red buttons that shows up after logging in (one for unlinking account; one for logout) could also be moved into header.

- [ ] Make the logout button another color and place somewhere else
- [ ] Place Unlink button somewhere else 

## Function

Have the buttons placed in a very intuitive place.

## Feature 

#52 : User Profile / Settings page | Header/Dashboard 

*Do not forget to set Epic, Milestone, and Estimate (1 = half workday)!*

**Comment by SaraSweetie** [comment]
@paulywill I have this started on a branch called [component-cleanup on my Fork](https://github.com/SaraSweetie/v8-geckos-team-07/tree/component-cleanup). I'm having trouble getting the Google user profile information (picture and name) appearing in the header-logged-in.js component. Did you get anywhere with this?

**Comment by paulywill** [comment]
@SaraSweetie not yet, working on it today
