### ISSUE TITLE
📝:  Move NewHabit.js/.css functionality to parent level (Dashboard.js)

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#66]
## Task Description

Move the functionality from NewHabit.js/.css to parent level (Dashboard.js/.css)

## Function
This will allow other forms (ie CheckIn #13 ) can inherit the same functionality and styling.

This includes the modal function @pjconnolly12 (@SaraSweetie ) are working on. -> #60 

## Feature 

#11 : New Habit 

*Do not forget to set Epic, Milestone, and Estimate (1 = half workday)!*

**Comment by pjconnolly12** [comment]
I just want to confirm, is this saying move the form to the Dashboard component? Personally I don't think that is the best in terms of React best practices. We want to try and keep components separate. We will be able to pass functionality through state and props. Let me know if anyone disagrees with this.

**Comment by paulywill** [comment]
@SaraSweetie ?

From our team meeting I thought the NewHabit component stays put... but some of the functions should be at the parent level and passed down ?

**Comment by paulywill** [comment]
#71 contains some of the work for this work item.

Still in QA & Review.

**Comment by SaraSweetie** [comment]
I think we need to move the functionality to App.js? That way we can use the state/props for both components (check-in.js and NewHabit.js)

We need to think through how the users are going to are going to access the NewHabit.js form. The check-in.js form is going to be accessed from Dashboard.js.
