### ISSUE TITLE
📝: Button to show CheckIn form (header / dashboard)

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#68]
## Task Description

Create and place an easy to see button that brings up the check-in form. Should be placed somewhere that makes sense.

## Function

Allows the user to "clock-in" habit report easily.

## Feature 

#13 - CheckIn form
#52 - Header/Dashboard

**Comment by paulywill** [comment]
@SaraSweetie @pjconnolly12 @patricktownley  Should this be a big plus sign icon?

https://www.google.com/search?q=icon+plus+button&tbm=isch

**Comment by pjconnolly12** [comment]
I am definitely for that. I probably won't pick the best one design wise so let me know if you have any suggestions and I can use that when I write the code. Thanks!

**Comment by paulywill** [comment]
> I am definitely for that. I probably won't pick the best one design wise so let me know if you have any suggestions and I can use that when I write the code. Thanks!

We can always return back to styling at the end. Well done with the feature!
