### ISSUE TITLE
📝: CheckIn Message: to indicated database was updated successfully

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#69]
## Task Description

A sucess message indicated data has been received and updated backend.

## Function

The message confirm to the user their request was successful. The can be a simple pop-up or a redirect to the stats page indicating most recent update.

## Feature 

#13

**Comment by paulywill** [comment]
@pjconnolly12 @patricktownley 
That additional popup message for the checkin essential accomplishes this correct?

Maybe going beyond scope... but is the submission confirmation modal happen after the dbase is updated?

For example is it possible the checkIn is submitted, the dbase does not update, but the confirmation message still appears?

Perhaps something to return to after MVP deadline... but are we confirming async situations with CRUD functions?

**Comment by pjconnolly12** [comment]
yes the additional pop-up handles this issue

We would need to do more testing to ensure the message only appears when it was successfully updated but based on everything I have seen so far it works properly. 

for MVP though I think it is good to go
