### ISSUE TITLE
📝: Edge case: navigating to /newhabit with no user defined

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#77]
## Task Description

Setup logic to prevent TypeError from showing up when navigating directly to /newhabit

## Function

if statement to prevent an error for a user that is not defined.

## Feature 

#11 - New Habit

**Comment by paulywill** [comment]
#82

**Comment by paulywill** [comment]
@pjconnolly12 Can we close this one?

Specifically does #87 New User Functionality resolve?

**Comment by pjconnolly12** [comment]
yes this can be closed, thanks!!
