### ISSUE TITLE
📝: Widget - Calendar

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#78]
## Task Description

Have a widget that shows a calendar with the various progress on it.

## Function

Shows the status in a simple calendar; should be able to progress the calendar for the duration of tracking period (set length or indefinite)

## Feature 

#14 - Progress/Stats

**Comment by paulywill** [comment]
https://www.npmjs.com/package/rc-calendar

**Comment by paulywill** [comment]
https://www.npmjs.com/package/react-calendar-heatmap

**Comment by paulywill** [comment]
https://www.jqueryscript.net/demo/Calendar-Heatmap-Plugin-jQuery/

Nice idea to break down big heatmap into separate months

**Comment by paulywill** [comment]
#103 resolved format of tool tip

On-click still has to be resolved. Ie showing checkin details

**Comment by patricktownley** [comment]
#106  submitted for checkin details
