### ISSUE TITLE
🐛: check in for that day not showing up in calendar

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#99]
Created a new habit and did a check-in.
Not reflected in the calendar... I suspect it will show up tomorrow.

Is something filtering out?

![image](https://user-images.githubusercontent.com/602422/57118005-44b2c300-6d2e-11e9-8782-36c64a5a6662.png)

![image](https://user-images.githubusercontent.com/602422/57118013-53997580-6d2e-11e9-87c5-f6c6376b0822.png)

**Comment by patricktownley** [comment]
It shows up for me but only after a refresh.

**Comment by patricktownley** [comment]
![image](https://user-images.githubusercontent.com/2468330/57181972-1fc26b00-6e68-11e9-8143-5415fd35bc50.png)


 I'm assuming I just need to tell the state to update after submitting a checkin.  Looking into this now.

**Comment by patricktownley** [comment]
Submitted #104
